#!/usr/bin/env python3
"""
Mock ATC tool for testing purposes
"""
import argparse
import os
import sys
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description='Mock ATC Tool')
    parser.add_argument('--framework', type=int, help='Framework type')
    parser.add_argument('--model', help='Input model file')
    parser.add_argument('--input_format', help='Input format')
    parser.add_argument('--output', help='Output directory')
    parser.add_argument('--log', help='Log level')
    parser.add_argument('--soc_version', help='SOC version')
    
    args = parser.parse_args()
    
    # Create output directory
    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Create a mock OM file
    om_file = output_dir / "model.om"
    with open(om_file, 'w') as f:
        f.write(f"Mock OM model converted from: {args.model}\n")
        f.write(f"Framework: {args.framework}\n")
        f.write(f"Input format: {args.input_format}\n")
        f.write(f"SOC version: {args.soc_version}\n")
        f.write("This is a test file generated by mock ATC\n")
    
    print(f"ATC run success")
    print(f"Input model: {args.model}")
    print(f"Output file: {om_file}")
    print(f"Framework: {args.framework}")
    print(f"SOC version: {args.soc_version}")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())